"""multi_tenancy

Revision ID: 924a00eab92b
Revises: d1f8a7e93000
Create Date: 2026-10-04 09:45:33.498617

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '924a00eab92b'
down_revision: Union[str, Sequence[str], None] = 'd1f8a7e93000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_organization_slug'), 'organization', ['slug'], unique=True)
    op.create_table('invitation',
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('invited_by_user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')", name='chk_invitation_role'),
    sa.ForeignKeyConstraint(['invited_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invitation_email'), 'invitation', ['email'], unique=False)
    op.create_index(op.f('ix_invitation_organization_id'), 'invitation', ['organization_id'], unique=False)
    op.create_index(op.f('ix_invitation_token_hash'), 'invitation', ['token_hash'], unique=True)
    op.create_table('membership',
    sa.Column('role', sa.Enum('OWNER', 'ADMIN', 'MEMBER', 'VIEWER', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("role IN ('OWNER', 'ADMIN', 'MEMBER', 'VIEWER')", name='chk_membership_role'),
    sa.ForeignKeyConstraint(['organization_id'], ['organization.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'organization_id', name='uq_membership_user_org')
    )
    op.create_index(op.f('ix_membership_organization_id'), 'membership', ['organization_id'], unique=False)
    op.create_index(op.f('ix_membership_user_id'), 'membership', ['user_id'], unique=False)
    op.add_column('incident', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.add_column('incident', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_incident_owner_id'), table_name='incident')
    op.create_index(op.f('ix_incident_organization_id'), 'incident', ['organization_id'], unique=False)
    op.drop_constraint(op.f('incident_owner_id_fkey'), 'incident', type_='foreignkey')
    op.create_foreign_key(None, 'incident', 'organization', ['organization_id'], ['id'])
    op.create_foreign_key(None, 'incident', 'user', ['created_by_user_id'], ['id'])
    op.drop_column('incident', 'owner_id')
    op.add_column('incident_updates', sa.Column('created_by_user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incident_updates', 'user', ['created_by_user_id'], ['id'])
    op.add_column('service', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_service_owner_id'), table_name='service')
    op.create_index(op.f('ix_service_organization_id'), 'service', ['organization_id'], unique=False)
    op.drop_constraint(op.f('product_owner_id_fkey'), 'service', type_='foreignkey')
    op.create_foreign_key(None, 'service', 'organization', ['organization_id'], ['id'])
    op.drop_column('service', 'owner_id')
    op.add_column('subscriber', sa.Column('organization_id', sa.Integer(), nullable=False))
    op.drop_index(op.f('ix_subscriber_owner_id'), table_name='subscriber')
    op.drop_constraint(op.f('uq_subscriber_owner_email'), 'subscriber', type_='unique')
    op.create_index(op.f('ix_subscriber_organization_id'), 'subscriber', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_subscriber_organization_email', 'subscriber', ['organization_id', 'email'])
    op.drop_constraint(op.f('subscriber_owner_id_fkey'), 'subscriber', type_='foreignkey')
    op.create_foreign_key(None, 'subscriber', 'organization', ['organization_id'], ['id'])
    op.drop_column('subscriber', 'owner_id')
    op.add_column('user', sa.Column('display_name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True))
    op.add_column('user', sa.Column('photo_url', sqlmodel.sql.sqltypes.AutoString(length=500), nullable=True))
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), nullable=False))
    op.add_column('user', sa.Column('firebase_uid', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False))
    op.drop_index(op.f('ix_user_organization_slug'), table_name='user')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.create_index(op.f('ix_user_firebase_uid'), 'user', ['firebase_uid'], unique=True)
    op.drop_column('user', 'organization_name')
    op.drop_column('user', 'hashed_password')
    op.drop_column('user', 'organization_slug')
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('organization_slug', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('hashed_password', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('user', sa.Column('organization_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_firebase_uid'), table_name='user')
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_index(op.f('ix_user_organization_slug'), 'user', ['organization_slug'], unique=True)
    op.drop_column('user', 'firebase_uid')
    op.drop_column('user', 'email_verified')
    op.drop_column('user', 'photo_url')
    op.drop_column('user', 'display_name')
    op.add_column('subscriber', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'subscriber', type_='foreignkey')
    op.create_foreign_key(op.f('subscriber_owner_id_fkey'), 'subscriber', 'user', ['owner_id'], ['id'])
    op.drop_constraint('uq_subscriber_organization_email', 'subscriber', type_='unique')
    op.drop_index(op.f('ix_subscriber_organization_id'), table_name='subscriber')
    op.create_unique_constraint(op.f('uq_subscriber_owner_email'), 'subscriber', ['owner_id', 'email'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_subscriber_owner_id'), 'subscriber', ['owner_id'], unique=False)
    op.drop_column('subscriber', 'organization_id')
    op.add_column('service', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'service', type_='foreignkey')
    op.create_foreign_key(op.f('product_owner_id_fkey'), 'service', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_service_organization_id'), table_name='service')
    op.create_index(op.f('ix_service_owner_id'), 'service', ['owner_id'], unique=False)
    op.drop_column('service', 'organization_id')
    op.drop_constraint(None, 'incident_updates', type_='foreignkey')
    op.drop_column('incident_updates', 'created_by_user_id')
    op.add_column('incident', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.drop_constraint(None, 'incident', type_='foreignkey')
    op.create_foreign_key(op.f('incident_owner_id_fkey'), 'incident', 'user', ['owner_id'], ['id'])
    op.drop_index(op.f('ix_incident_organization_id'), table_name='incident')
    op.create_index(op.f('ix_incident_owner_id'), 'incident', ['owner_id'], unique=False)
    op.drop_column('incident', 'created_by_user_id')
    op.drop_column('incident', 'organization_id')
    op.drop_index(op.f('ix_membership_user_id'), table_name='membership')
    op.drop_index(op.f('ix_membership_organization_id'), table_name='membership')
    op.drop_table('membership')
    op.drop_index(op.f('ix_invitation_token_hash'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_organization_id'), table_name='invitation')
    op.drop_index(op.f('ix_invitation_email'), table_name='invitation')
    op.drop_table('invitation')
    op.drop_index(op.f('ix_organization_slug'), table_name='organization')
    op.drop_table('organization')
    # ### end Alembic commands ###
